### ISSUE TITLE
Knapp, bare gul

### ISSUE THREAD

**Issue by JulieHM** [Burhan-Mohammad-Sarfraz/generic-high-score-local-api#13]
Skal bare trenge å bruke den gule knappen i labyrinten for å starte timeren (spillet). 
Da kan vi fjerne "aktiver"/start knappen i frontend

**Comment by williams-ye-bouvet** [comment]
Kinda fiksa, må fortsatt klikke en gang på starte. Vet heller ikke hvordan den funker med submit form
