### ISSUE TITLE
Fikse form i frontend

### ISSUE THREAD

**Issue by JulieHM** [Burhan-Mohammad-Sarfraz/generic-high-score-local-api#14]
- fikse margin mellom label og input felt
- Gjøre at form lukkes når man trykker "Send" 
- validering på navn, ikke grense på 10 tegn
- + litt justeringer css

**Comment by Burhan-Mohammad-Sarfraz** [comment]
Jeg fjernet begrensningen på lengde på navnet fra backend. Endring i branchen _remove__username__length__restriction_
