### ISSUE TITLE
Fikse at backend ikke krasjer

### ISSUE THREAD

**Issue by JulieHM** [Burhan-Mohammad-Sarfraz/generic-high-score-local-api#20]
Vi opplevde at backend tryna 3-4 ganger hver dag. Tok dessverre ikke vare på feilmelding, men det var relatert til skriving til til json filen

**Comment by Burhan-Mohammad-Sarfraz** [comment]
Tror denne er ferdig, men vanskelig å sjekke uten å vite konkret feilmelding. Får se når vi gjør omfattende testing
